package com.idorsia.research.send.terminology;

public enum UnitTerm {
	
	POURCENTAGE("%"),
	POURCENTAGE_INHIBITION("% INHIBITION"),
	POURCENTAGE_VV("%(v/v)"),
	POURCENTAGE_WV("%(w/v)"),
	POURCENTAGE_WW("%(w/w)"),
	POURCENTAGE_MIN("%/min"),
	POURCENTAGE_S("%/s"),
	HUNDRED_HPFS("/100 HPFs"),
	HUNDRED_WBC("/100 WBC"),
	HUNDRED_10P3("/10^3"),
	HUNDRED_10P4("/10^4"),
	HUNDRED_10P5("/10^5"),
	/*("/200 HPFs"),
	("/2000 RBC"),
	("/2500 WBC"),
	("/4.0 mL"),
	("/40 HPFs"),
	("/500 WBC"),
	("/7.5 mL"),
	("/cmH2O"),
	("/day"),
	("/h"),
	("/HPF"),
	("/kg"),
	("/LPF"),
	("/LSQN"),
	("/min"),
	("/mm"),
	("/mm2"),
	("/month"),
	("/ms"),
	("/sec"),
	("/VF"),
	("/wk"),
	("1/(s*kPa)"),
	("100 IU/mL"),
	("10^10/L"),
	("10^11/L"),
	("10^12 IU/L"),
	("10^12/L"),
	("10^3 CFU"),
	("10^3 CFU/g"),
	("10^3 CFU/mL"),
	("10^3 copies/mL"),
	("10^3 DNA copies/mL"),
	("10^3 organisms"),
	("10^3 organisms/g"),
	("10^3 organisms/mL"),
	("10^3 RNA copies/mL"),
	("10^3/hpf"),
	("10^3/L"),
	("10^4 CFU"),
	("10^4/hpf"),
	("10^4/L"),
	("10^5/hpf"),
	("10^5/L"),
	("10^6 CFU"),
	("10^6 CFU/g"),
	("10^6 CFU/mL"),
	("10^6 copies/mL"),
	("10^6 DNA copies/mL"),
	("10^6 IU"),
	("10^6 IU/mL"),
	("10^6 organisms"),
	("10^6 organisms/g"),
	("10^6 organisms/mg"),
	("10^6 organisms/mL"),
	("10^6 RNA copies/mL"),
	("10^6 U"),
	("10^6/Ejaculate U"),
	("10^6/g"),
	("10^6/hpf"),
	("10^6/L"),
	("10^7 CFU"),
	("10^7/L"),
	("10^8/L"),
	("10^9 CFU"),
	("10^9 CFU/g"),
	("10^9 CFU/mL"),
	("10^9 organisms"),
	("10^9 organisms/g"),
	("10^9 organisms/mg"),
	("10^9 organisms/mL"),
	("10^9/dose"),
	("10^9/g"),
	("10^9/L"),
	("Absorbance U"),
	("Absorbance U/min"),
	("Absorbance U/mL"),
	("AFU"),
	("ag"),
	("AgU/mL"),
	("aMFI"),
	("amol"),
	("amp"),
	("AMPULE"),
	("amu"),
	("Anson U"),
	("anti-Xa IU"),
	("anti-Xa IU/mL"),
	("Antibody Unit"),
	("APL U"),
	("APL U/mL"),
	("APPLICATION"),
	("APS U"),
	("Arbitrary U"),
	("atm"),
	("AU/mL"),
	("BAG"),
	("BAR"),
	("BAU"),
	("BAU/mL"),
	("BE/mL"),
	("BEAM BREAKS"),
	("beats/min"),
	("bel"),
	("BISCUIT"),
	("BLOCKS"),
	("BOLUS"),
	("BOTTLE"),
	("BOX"),
	("BP"),
	("Bq"),
	("Bq/g"),
	("Bq/kg"),
	("Bq/L"),
	("Bq/mg"),
	("Bq/mL"),
	("Bq/ug"),
	("Bq/uL"),
	("breaths/min"),
	("BU"),
	("BU/mL"),
	("C"),
	("cal"),
	("CAN"),
	("CAPFUL"),
	("CAPLET"),
	("CAPSULE"),
	("CARTRIDGE"),
	("CCID 50/dose"),
	("CCID 50/mL"),
	("cd"),
	("cd*s/m2"),
	("cd/m2"),
	("CFU/g"),
	("CFU/mL"),
	("cg"),
	("cGy"),
	("Ci"),
	("Ci/g"),
	("Ci/kg"),
	("Ci/L"),
	("Ci/mg"),
	("Ci/mL"),
	("Ci/ug"),
	("Ci/uL"),
	("CIGAR"),
	("CIGARETTE"),
	("cL"),
	("cm"),
	("cm H2O"),
	("cm/min"),
	("cm/s"),
	("cm2"),
	("cmH2O*s/mL"),
	("cmH2O*s2/mL"),
	("cmH2O/mL"),
	("cmHg"),
	("cmol"),
	("cmol/L"),
	("COAT"),
	("CONTAINER"),
	("copies/mL"),
	("copies/ug"),
	("copies/uL"),
	("Coulomb"),
	("cP"),
	("cpm"),
	("cs"),
	("CUP"),
	("cy/cm"),
	("cycle/min"),
	("CYLINDER"),
	("DAgU"),
	("DAgU/mL"),
	("damol/L"),
	("DAYS"),
	("dB"),
	("DDU"),
	("deg"),
	("deg/mm"),
	("DIOPTER"),
	("DIP"),
	("DISK"),
	("dL"),
	("dmol"),
	("DNA copies/mL"),
	("DPM"),
	("dpm/0.5 mL"),
	("dpm/100mg"),
	("dpm/mg"),
	("dpm/mL"),
	("dram"),
	("DRINK"),
	("DROP"),
	("DRUM"),
	("dyn"),
	("ECL unit"),
	("EIA unit"),
	("EID 50/dose"),
	("EID 50/mL"),
	("Ejaculate U"),
	("ELISA unit"),
	("ELISA unit/dose"),
	("ELISA unit/mL"),
	("Enzyme U"),
	("Enzyme U/g Hb"),
	("Enzyme U/L"),
	("Enzyme U/m2"),
	("eq"),
	("EU"),
	("EVENTS"),
	("F"),
	("Farad"),
	("FEU"),
	("FFU"),
	("fg"),
	("FINGERTIP UNIT"),
	("FIU"),
	("fL"),
	("fmol"),
	("fmol/g"),
	("fmol/L"),
	("fmol/L/sec"),
	("foz_br"),
	("foz_us"),
	("fraction of 1"),
	("Frames/s"),
	("ft"),
	("ft2"),
	("ft3"),
	("g"),
	("g/animal"),
	("g/animal/day"),
	("g/animal/wk"),
	("g/cage"),
	("g/cage/day"),
	("g/cage/wk"),
	("g/cm2"),
	("g/day"),
	("g/dL"),
	("g/g"),
	("g/g/day"),
	("g/kg"),
	("g/kg/day"),
	("g/L"),
	("g/m2"),
	("g/m2/day"),
	("g/mol"),
	("Gauss"),
	("GBq"),
	("GBq/g"),
	("GBq/mg"),
	("GBq/ug"),
	("genEq"),
	("genEq/mL"),
	("GLOBULE"),
	("gMFI"),
	("gpELISA unit/mL"),
	("GPL U"),
	("GPL U/mL"),
	("GPS U"),
	("grain"),
	("Gravitational Unit"),
	("gtt"),
	("Gy"),
	("Gy/h"),
	("Gy/min"),
	("h*%"),
	("Henry"),
	("HEP"),
	("HOMEOPATHIC DILUTION"),
	("Hounsfield Unit"),
	("HOURS"),
	("hPa"),
	("Hz"),
	("Hz/s"),
	("IMPLANT"),
	("in"),
	("in2"),
	("INHALATION"),
	("IU"),
	("IU/day"),
	("IU/dL"),
	("IU/g"),
	("IU/g Hb"),
	("IU/kg"),
	("IU/kg/h"),
	("IU/L"),
	("IU/mg"),
	("IU/mL"),
	("IU/mmol"),
	("JAR"),
	("Joule"),
	("K"),
	("ka_u/dL"),
	("KALLIKREIN INHIBITOR UNIT"),
	("kat"),
	("kBq"),
	("kBq/uL"),
	("kcal"),
	("kcal/day"),
	("kDa"),
	("keV"),
	("kg"),
	("kg/cm"),
	("kg/cm2"),
	("kg/L"),
	("kg/m2"),
	("kg/mol"),
	("kHz"),
	("KIT"),
	("kIU"),
	("km"),
	("km/h"),
	("kN/cm2"),
	("kPa"),
	("kPa/L/sec"),
	("ks"),
	("kUSP"),
	("L"),
	("L/day"),
	("L/h"),
	("L/h/m2"),
	("L/kg"),
	("L/L"),
	("L/min"),
	("L/min/m2"),
	("L/s"),
	("L/s/kPa"),
	("LB"),
	("Linear ft*LB"),
	("lm"),
	("log EID 50/dose"),
	("log10 CCID 50/dose"),
	("log10 CFU/g"),
	("log10 CFU/mL"),
	("log10 copies/mL"),
	("Log10 ELISA unit"),
	("Log10 ELISA unit/dose"),
	("log10 IU/mL"),
	("log10 TCID 50/dose"),
	("log10 TCID 50/mL"),
	("log10 TCID 50/uL"),
	("LOZENGE"),
	("lx"),
	("m"),
	("m/sec"),
	("m/sec2"),
	("m2"),
	("m3"),
	("MAC50"),
	("mAmp"),
	("mAnson U/mL"),
	("MBq"),
	("MBq/uL"),
	("mCi"),
	("mCi/kg"),
	("mCi/L"),
	("MdFI"),
	("mEq"),
	("mEq/day"),
	("mEq/dL"),
	("mEq/g"),
	("mEq/kg"),
	("mEq/L"),
	("mEq/mL"),
	("mEq/mmol"),
	("mEq/ug"),
	("mEq/uL"),
	("MESF"),
	("MET"),
	("MET*h"),
	("MET*min"),
	("mg"),
	("mg/animal"),
	("mg/cm2"),
	("mg/day"),
	("mg/dL"),
	("mg/dose"),
	("mg/g/h"),
	("mg/g/min"),
	("mg/h"),
	("mg/kg"),
	("mg/kg/day"),
	("mg/kg/dose"),
	("mg/kg/h"),
	("mg/kg/min"),
	("mg/kg/week"),
	("mg/L"),
	("mg/L FEU"),
	("mg/m2"),
	("mg/m2/day"),
	("mg/m2/h"),
	("mg/m2/min"),
	("mg/min"),
	("mg/mL/min"),
	("mg/mol"),
	("mg2/dL2"),
	("mgEq"),
	("MHz"),
	("Mile"),
	("min"),
	("mIU/L"),
	("mJoule/cm2"),
	("mkat"),
	("mL"),
	("mL*cmH2O"),
	("mL/(min*100mL)"),
	("mL/100g/min"),
	("mL/animal"),
	("mL/animal/day"),
	("mL/animal/wk"),
	("mL/beat"),
	("mL/breath"),
	("mL/cage"),
	("mL/cage/day"),
	("mL/cage/wk"),
	("mL/cm"),
	("mL/cm H2O"),
	("mL/cm3/min"),
	("mL/day"),
	("mL/dL"),
	("mL/dose"),
	("mL/g/day"),
	("mL/g/h"),
	("mL/g/min"),
	("mL/h"),
	("mL/kg"),
	("mL/kg/day"),
	("mL/kg/h"),
	("mL/kg/min"),
	("mL/m2"),
	("mL/m2/day"),
	("mL/m2/h"),
	("mL/m2/min"),
	("mL/min"),
	("mL/min/1.73m2"),
	("mL/min/mmHg"),
	("mL/mmHg"),
	("mL/mmHg/min/L"),
	("mL/s"),
	("mL/sec/1.73m2"),
	("mm"),
	("mm/2h"),
	("mm/h"),
	("mm/min"),
	("mm/sec"),
	("mm2"),
	("mm3/mm2/year"),
	("mmAL"),
	("mmHg"),
	("mmHg*min/L"),
	("mmHg/L/min"),
	("mmHg/sec"),
	("mmol"),
	("mmol/day"),
	("mmol/g"),
	("mmol/kg"),
	("mmol/L"),
	("mmol/min/kPa"),
	("mmol/min/kPa/L"),
	("mmol/mol"),
	("mmol/s"),
	("mmol2/L2"),
	("mMU/mL"),
	("mN"),
	("MnFI"),
	("mol"),
	("mol/day"),
	("mol/g"),
	("mol/L"),
	("mol/mg"),
	("mol/mL"),
	("mol/mol"),
	("MONTHS"),
	("mOsm"),
	("mOsm/kg"),
	("mOsm/L"),
	("mPa"),
	("mph"),
	("MPL U"),
	("MPL U/mL"),
	("MPS U"),
	("ms/mmHg"),
	("ms2"),
	("msec"),
	("mU/g"),
	("mU/L"),
	("mV"),
	("mV*min"),
	("mV/sec"),
	("mV2/Hz"),
	("nCi"),
	("NEBULE"),
	("NEEDLE GAUGE"),
	("Newton"),
	("NFIU"),
	("ng"),
	("ng/day"),
	("ng/dL"),
	("ng/L"),
	("ngEq/L"),
	("nkat"),
	("nkat/L"),
	("nL"),
	("nm"),
	("nmol"),
	("nmol BCE/L"),
	("nmol BCE/mmol"),
	("nmol BCE/nmol"),
	("nmol/day"),
	("nmol/g"),
	("nmol/L"),
	("nmol/L/h"),
	("nmol/L/min"),
	("nmol/mL/min"),
	("nmol/mol"),
	("nsec"),
	("nU/cL"),
	("OD Unit"),
	("ohm"),
	("OI50"),
	("osm"),
	("oz"),
	("P"),
	("PA"),
	("Pa"),
	("PACK"),
	("Pack Year"),
	("PACKAGE"),
	("PACKET"),
	("PATCH"),
	("PELLET"),
	("PFU"),
	("PFU/animal"),
	("PFU/dose"),
	("PFU/mL"),
	("pg"),
	("pg/dL"),
	("pg/L"),
	("PHERESIS UNIT"),
	("PIPE"),
	("PIXEL"),
	("PIXELS/cm"),
	("PIXELS/in"),
	("pkat"),
	("pkat/L"),
	("pL"),
	("pm"),
	("pmol"),
	("pmol/10^10 cells"),
	("pmol/10^9 cells"),
	("pmol/day"),
	("pmol/dL"),
	("pmol/g"),
	("pmol/L"),
	("pmol/L/h"),
	("PNU/mL"),
	("POINT"),
	("POUCH"),
	("ppb"),
	("ppm"),
	("ppth"),
	("pptr"),
	("PRESSOR UNITS"),
	("psec"),
	("psi"),
	("pt_br"),
	("pt_us"),
	("PUFF"),
	("QUANTITY SUFFICIENT"),
	("Rad"),
	("RATIO"),
	("RFU"),
	("RING"),
	("RNA copies/mL"),
	("Roentgen"),
	("rpm"),
	("s*kPa"),
	("s/h"),
	("s^-1(%O2)^-1"),
	("SACHET"),
	("SBE/mL"),
	("scm"),
	("SCOOPFUL"),
	("sec"),
	("SFC/10^6 PBMC"),
	("Shock Wave"),
	("Siemens"),
	("SPRAY"),
	("SQU/mL"),
	("STEPS"),
	("STRIP"),
	("SUPPOSITORY"),
	("Sv"),
	("SYRINGE"),
	("TABLET"),
	("TAMPON"),
	("Tbsp"),
	("TCID 50/dose"),
	("Tesla"),
	("titer"),
	("Torr"),
	("TRACE"),
	("TRANSDUCING UNIT"),
	("TRANSDUCING UNIT/mL"),
	("TROCHE"),
	("tsp"),
	("TUBE"),
	("tuberculin unit"),
	("tuberculin unit/mL"),
	("U"),*/
	U_CARR("U.CARR"),
	U_10P12_RBC("U/10^12 RBC"),
	U_ANIMAL("U/animal"),
	U_CL("U/cL"),
	U_DL("U/dL"),
	U_G("U/g"),
	U_G_HB("U/g Hb"),
	U_G_DAY("U/g/day"),
	U_G_H("U/g/h"),
	U_G_MIN("U/g/min"),
	U_KG("U/kg"),
	U_KG_DAY("U/kg/day"),
	U_KG_H("U/kg/h"),
	U_KG_MIN("U/kg/min"),
	U_L("U/L"),
	U_M2("U/m2"),
	U_M2_DAY("U/m2/day"),
	U_M2_H("U/m2/h"),
	U_M2_MIN("U/m2/min"),
	U_MG("U/mg"),
	U_ML("U/mL"),
	U_MMOL("U/mmol"),
	UCI("uCi"),
	UCI_KG("uCi/kg"),
	UCI_L("uCi/L"),
	UEQ("uEq"),
	UEQ_L("uEq/L"),
	UG("ug"),
	UG_ANIMAL("ug/animal"),
	UG_CM2("ug/cm2"),
	UG_DAY("ug/day"),
	UG_DL("ug/dL"),
	UG_DOSE("ug/dose"),
	UG_G_DAY("ug/g/day"),
	UG_G_H("ug/g/h"),
	UG_G_MIN("ug/g/min"),
	UG_H("ug/h"),
	UG_KG("ug/kg"),
	UG_KG_DAY("ug/kg/day"),
	UG_KG_H("ug/kg/h"),
	UG_KG_MIN("ug/kg/min"),
	UG_L("ug/L"),
	UG_L_DDU("ug/L DDU"),
	UG_L_FEU("ug/L FEU"),
	UG_L_H("ug/L/h"),
	UG_M2("ug/m2"),
	UG_M2_DAY("ug/m2/day"),
	UG_M2_H("ug/m2/h"),
	UG_M2_MIN("ug/m2/min"),
	UG_MIN("ug/min"),
	UG_ML_H("ug/mL/h"),
	UGEQ("ugEq"),
	UGEQ_l("ugEq/L"),
	UIU_DL("uIU/dL"),
	UIU_L("uIU/L"),
	UKAT("ukat"),
	UKAT_10P12_RBC("ukat/10^12 RBC"),
	UKAT_L("ukat/L"),
	UL("uL"),
	UL_DOSE("uL/dose"),
	UL_KG_DAY("uL/kg/day"),
	UL_ML("uL/mL"),
	UM("um"),
	UM_DAY("um/day"),
	UM_S("um/s"),
	UM2("um2"),
	UMOL("umol"),
	UMOL_DAY("umol/day"),
	UMOL_DL("umol/dL"),
	UMOL_H_MMOL("umol/h/mmol"),
	UMOL_KG_MIN("umol/kg/min"),
	UMOL_L("umol/L"),
	UMOL_L_H("umol/L/h"),
	UMOL_L_MIN("umol/L/min"),
	UMOL_L_SEC("umol/L/sec"),
	UMOL_MG_MIN("umol/mg/min"),
	UMOL_MIN("umol/min"),
	UMOL_MOL("umol/mol"),
	UOSM("uOsM"),
	USEC("usec"),
	USIEMENS("uSiemens"),
	USP_U("USP U"),
	UU_DL("uU/dL"),
	UU_L("uU/L"),
	UV("uV"),
	UV_SEC("uV*sec"),
	V("V"),
	V_SEC("V/sec"),
	V_V("v/v"),
	VG_DOSE("vg/dose"),
	VG_KG("vg/kg"),
	VG_ML("vg/mL"),
	VIAL("VIAL"),
	VIRTUAL_PIXEL("VIRTUAL PIXEL"),
	VOXEL("VOXEL"),
	VP_DOSE("vp/dose"),
	VP_ML("vp/mL"),
	WAFER("WAFER"),
	WATT("Watt"),
	WEBER("Weber"),
	WEEKS("WEEKS"),
	YD("yd"),
	YEARS("YEARS");

	private String value;

	UnitTerm(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
	
}
